server:
  port: 8081

spring:
  application:
    name: task-tracker-email-sender
  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: email-sender-group
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true