spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml

application:
  name: task-tracker-backend
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${EXPIRATION}
